### ISSUE TITLE
Sprites with a width of 1 cause errors.

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#253] opened 2016-03-05 15:47 UTC
```
Operating System: Linux
Version: 3.19.0-49-generic
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_95

Available processors (cores): 4
Free memory (bytes): 114586816
Maximum memory (bytes): 620756992
Total memory available to JVM (bytes): 279445504

File system root: /
Total space (bytes): 28875468800
Free space (bytes): 7771738112
Usable space (bytes): 6281314304

Stack trace:
java.lang.IllegalArgumentException: Width (0) and height (6) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:331)
	at org.lateralgm.main.Util.paintBackground(Util.java:105)
	at org.lateralgm.main.Util.paintBackground(Util.java:126)
	at org.lateralgm.subframes.SpriteFrame$ImageCellRenderer.getListCellRendererComponent(SpriteFrame.java:740)
	at org.lateralgm.subframes.SpriteFrame$ImageCellRenderer.getListCellRendererComponent(SpriteFrame.java:1)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1360)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1310)
	at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2622)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(DefaultListSelectionModel.java:576)
	at javax.swing.DefaultListSelectionModel.clearSelection(DefaultListSelectionModel.java:420)
	at javax.swing.JList.clearSelection(JList.java:2045)
	at javax.swing.JList.setModel(JList.java:1679)
	at javax.swing.JList.setListData(JList.java:1697)
	at org.lateralgm.subframes.SpriteFrame.updateImageList(SpriteFrame.java:1644)
	at org.lateralgm.subframes.SpriteFrame.updated(SpriteFrame.java:1715)
	at org.lateralgm.main.UpdateSource$WeakListenerTraverser.visit(UpdateSource.java:137)
	at org.lateralgm.main.UpdateSource$WeakListenerTraverser.visit(UpdateSource.java:1)
	at org.lateralgm.util.SetTraverser.traverse(SetTraverser.java:72)
	at org.lateralgm.main.UpdateSource.fireUpdate(UpdateSource.java:63)
	at org.lateralgm.main.UpdateSource.access$0(UpdateSource.java:61)
	at org.lateralgm.main.UpdateSource$UpdateTrigger.fire(UpdateSource.java:98)
	at org.lateralgm.resources.Resource.fireUpdate(Resource.java:110)
	at org.lateralgm.resources.Sprite.fireUpdate(Sprite.java:282)
	at org.lateralgm.resources.Sprite$ImageList.set(Sprite.java:453)
	at org.lateralgm.resources.Sprite$ImageList.replace(Sprite.java:399)
	at org.lateralgm.subframes.SpriteFrame$ImageEditor.updated(SpriteFrame.java:1787)
	at org.lateralgm.main.UpdateSource$WeakListenerTraverser.visit(UpdateSource.java:137)
	at org.lateralgm.main.UpdateSource$WeakListenerTraverser.visit(UpdateSource.java:1)
	at org.lateralgm.util.SetTraverser.traverse(SetTraverser.java:72)
	at org.lateralgm.main.UpdateSource.fireUpdate(UpdateSource.java:63)
	at org.lateralgm.main.UpdateSource.access$0(UpdateSource.java:61)
	at org.lateralgm.main.UpdateSource$UpdateTrigger.fire(UpdateSource.java:103)
	at org.lateralgm.file.FileChangeMonitor$UpdateRunnable.run(FileChangeMonitor.java:114)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

java.lang.IllegalArgumentException: Width (0) and height (6) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:331)
	at org.lateralgm.main.Util.paintBackground(Util.java:105)
	at org.lateralgm.main.Util.paintBackground(Util.java:126)
	at org.lateralgm.subframes.SpriteFrame$ImageCellRenderer.getListCellRendererComponent(SpriteFrame.java:740)
	at org.lateralgm.subframes.SpriteFrame$ImageCellRenderer.getListCellRendererComponent(SpriteFrame.java:1)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1360)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1310)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:577)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1652)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:790)
	at java.awt.Container.layout(Container.java:1503)
	at java.awt.Container.doLayout(Container.java:1492)
	at java.awt.Container.validateTree(Container.java:1688)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validate(Container.java:1623)
	at javax.swing.RepaintManager$2.run(RepaintManager.java:691)
	at javax.swing.RepaintManager$2.run(RepaintManager.java:689)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:688)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1676)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

java.lang.IllegalArgumentException: Width (0) and height (6) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:331)
	at org.lateralgm.main.Util.paintBackground(Util.java:105)
	at org.lateralgm.main.Util.paintBackground(Util.java:126)
	at org.lateralgm.components.visual.SubimagePreview.paintComponent(SubimagePreview.java:105)
	at javax.swing.JComponent.paint(JComponent.java:1046)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
	at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by RobertBColton** [comment] 2016-03-24 09:30
Closing as duplicate of #199 and because this is fixed in master.

**Closed by RobertBColton** 2016-03-24 09:30 UTC
