### ISSUE TITLE
Image duplication then edit edits wrong image

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#304] opened 2016-07-02 10:21 UTC
To reproduce:  
1. Have an image in a sprite.  
2. Select the first image.
3. Copy and paste that image into the sprite to duplicate it.  
4. Double click the last image to edit it.  
5. Save the image.  
6. The image will be saved to the image that is before the selected image, rather than to the selected image.

**Comment by RobertBColton** [comment] 2016-09-29 16:56
This is definitely reproducible. It looks like what is happening is that as soon as the external image editor opens the image, the subimage list has its selection removed over in LGM. So you can actually reproduce the issue this way too:

1. Create a sprite
2. Add a bunch of blank subimages
3. Double click on one of the subimages in the middle to open the external editor
4. When the external editor opens, switch back to LGM
5. Notice the selection on the subimage list in the sprite editor is removed

**Comment by RobertBColton** [comment] 2018-03-02 03:18
Ok, so this was always two issues together. First, the paste action was a shallow clone, and should have been a deep copy (causing the reported issue). Second, the file change monitor was capturing the wrong last modified time and file length (causing the unreported issue with the list selection index being lost).

**Comment by RobertBColton** [comment] 2018-03-02 17:08
Ok, both of these issues are resolved in a new release:
https://github.com/IsmAvatar/LateralGM/releases

Closing as resolved.

**Closed by RobertBColton** 2018-03-02 17:08 UTC
Labels: Bug, Confirmed, Editor, Reproducible, Task
