### ISSUE TITLE
LateralGM error when i try open a game maker 8 project.

### ISSUE THREAD

**Issue by ZazonGames** [IsmAvatar/LateralGM#465] opened 2020-01-20 20:19 UTC
My LateralGM gets a bug when i try open a game maker 8/8.1 file.
The error is that:

LateralGM Version: 1.8.89
Working Directory: C:\GameMaker\lateralgm.jar

Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_201

Current Thread: Thread-4
Available processors (cores): 2
Free memory (bytes): 170385984
Maximum memory (bytes): 3689414656
Total memory available to JVM (bytes): 200278016

File system root: C:\
Total space (bytes): 999007711232
Free space (bytes): 224141189120
Usable space (bytes): 224141189120

Stack trace:
org.lateralgm.file.GmFormatException: java.io.IOException: Unexpected end of file reached at filepos: 19382
	at org.lateralgm.file.StreamDecoder.read(StreamDecoder.java:64)
	at org.lateralgm.file.StreamDecoder.read(StreamDecoder.java:55)
	at org.lateralgm.file.iconio.BitmapRGB32BPP.readBitmap(BitmapRGB32BPP.java:42)
	at org.lateralgm.file.iconio.AbstractBitmapRGB.read(AbstractBitmapRGB.java:33)
	at org.lateralgm.file.iconio.ICOFile.readBitmap(ICOFile.java:297)
	at org.lateralgm.file.iconio.ICOFile.fillDescriptor(ICOFile.java:217)
	at org.lateralgm.file.iconio.ICOFile.fillDescriptors(ICOFile.java:198)
	at org.lateralgm.file.iconio.ICOFile.read(ICOFile.java:164)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:129)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:112)
	at org.lateralgm.file.GmFileReader.readSettings(GmFileReader.java:434)
	at org.lateralgm.file.GmFileReader.readProjectFile(GmFileReader.java:230)
	at org.lateralgm.file.GmFileReader.readProjectFile(GmFileReader.java:168)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:391)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:630)
	at java.lang.Thread.run(Unknown Source)

**Comment by JoshDreamland** [comment] 2020-01-21 00:33
The error suggests your file is truncated. Does it open correctly in old versions of Game Maker?

**Comment by ZazonGames** [comment] 2020-01-21 19:46
you mean open files in the normal game maker 8,yes

**Comment by RobertBColton** [comment] 2020-01-28 19:39
Try one of the older releases please.
https://github.com/IsmAvatar/LateralGM/releases

It seems I made some changes to ICO reading, not sure if it's the cause.

**Comment by RobertBColton** [comment] 2020-02-13 03:38
@ZazonGames any luck or can you provide the project file please?

**Comment by ZazonGames** [comment] 2020-02-15 15:53
Sorry for late reply.No lucky,and no i cant because it is private sorry.There is any other way.bassicly when i open any project of gm8,it gave that error

**Comment by JoshDreamland** [comment] 2020-02-15 17:12
Unfortunate. If you have time, you can try copying the file and deleting resources until you figure out which one is giving LGM issues, then scrub and share that. Otherwise, there isn't much we can do.

**Comment by RobertBColton** [comment] 2020-02-15 21:29
Alright, that's fine, but you or somebody will need to provide me with some GM8 or GM81 that reproduces it in order for me to fix it. I have several locally myself and they do not seem to reproduce this error.

**Comment by RobertBColton** [comment] 2020-07-05 19:08
@ZazonGames Could you please try to open the game in GameMaker 8 and then open Global Game Settings? Do any errors occur when you open the Global Game Settings?

**Comment by ZazonGames** [comment] 2020-07-17 19:42
oops im sorry i forgot to reply.
i do not have the problem anymore in the newest version.

**Comment by RobertBColton** [comment] 2020-07-19 07:38
Alright then, closing as resolved. I dug into the git blame and was not able to ascertain what change actually corrected the issue. I'm sure it isn't being sunk because then you still would not be able to load any usable part of the project since settings come first and an exception there would terminate too early to load any other resource.

There has been no other change to read settings or the ICOFile class since the version (v1.8.89 from October 5th 2019) you originally reported. I believe that you must have saved the project back out from GM8 and that corrected whatever the issue was in the file.

Regardless, please try to include minimally reproducible game files in future bug reports because they really make this process a lot easier to fix issues. Thank you!

**Closed by RobertBColton** 2020-07-19 07:38 UTC
Labels: Error, File Reader
