### ISSUE TITLE
Issue importing a GM:Studio project

### ISSUE THREAD

**Issue by BeepBoop486** [IsmAvatar/LateralGM#451] opened 2019-09-24 18:51 UTC
LateralGM Version: 1.8.85
Working Directory: /home/nothers/enigma-dev/lateralgm.jar

Operating System: Linux
Version: 4.19.0-6-amd64
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_221

Available processors (cores): 2
Free memory (bytes): 42601648
Maximum memory (bytes): 889192448
Total memory available to JVM (bytes): 138412032

File system root: /
Total space (bytes): 486566535168
Free space (bytes): 297471361024
Usable space (bytes): 272683708416

Stack trace:
org.lateralgm.file.GmFormatException: failed to read: /home/nothers/Descargas/Geometry Dash.gmz_FILES/Configs\Default\windows\runner_icon.ico
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:530)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:299)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:237)
	at org.lateralgm.main.FileChooser$GMXIO.read(FileChooser.java:496)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:630)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /home/nothers/Descargas/Geometry Dash.gmz_FILES/Configs/Default/windows/runner_icon.ico (No existe el fichero o el directorio)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.lateralgm.file.StreamDecoder.<init>(StreamDecoder.java:45)
	at org.lateralgm.file.iconio.ICOFile.<init>(ICOFile.java:75)
	at org.lateralgm.file.GMXFileReader.readConfigurations(GMXFileReader.java:526)
	... 5 more

**Comment by BeepBoop486** [comment] 2019-09-24 18:54
[g++] SHELLmain.cpp
In file included from [01m[KSHELLmain.cpp:106[m[K:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:[m[K In function ‘[01m[Kvariant roomcreate1()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:103:1:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_colour[m[K’ was not declared in this scope
 [01;31m[Kbackground_colour[m[K = c_black;
 [01;31m[K^~~~~~~~~~~~~~~~~[m[K
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:[m[K In function ‘[01m[Kvariant roomcreate2()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:320:1:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_colour[m[K’ was not declared in this scope
 [01;31m[Kbackground_colour[m[K = c_black;
 [01;31m[K^~~~~~~~~~~~~~~~~[m[K
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:[m[K In function ‘[01m[Kvariant roomcreate3()[m[K’:
[01m[K/home/nothers/.enigma/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:1001:1:[m[K [01;31m[Kerror: [m[K‘[01m[Kbackground_colour[m[K’ was not declared in this scope
 [01;31m[Kbackground_colour[m[K = c_black;
 [01;31m[K^~~~~~~~~~~~~~~~~[m[K
make[1]: *** [Makefile:177: /home/nothers/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/SHELLmain.o] Error 1
make[1]: se sale del directorio '/home/nothers/enigma-dev/ENIGMAsystem/SHELL'
make: *** [Makefile:22: Game] Error 2
2

**Comment by RobertBColton** [comment] 2019-09-28 03:00
The runner icon was missing from the project's config folder.

**Comment by RobertBColton** [comment] 2019-09-28 03:16
Ok, I managed to reproduce your issue with GMZ there. GMS does not export the runner icon for a config to the GMZ if you are using the default icon. Only if you use your own icon does GMS export it in the GMZ. This is a problem because LGM expects an ico file to always be there. I'll see about patching LGM so we put our default icon on the project when the file does not exist.

**Comment by RobertBColton** [comment] 2020-07-19 17:30
Closing as resolved by 95ca8a28b75ed66e7a9bbbd021a28a13aea6ba50 which switches over to the GMSv1.4 behavior. You can now download the latest 1.8.157 release with the patch.

**Closed by RobertBColton** 2020-07-19 17:30 UTC
Labels: Confirmed, Error, File Reader, Reproducible
