### ISSUE TITLE
[OpenJDK 9 regression] LateralGM don't work - No Splashscreen

### ISSUE THREAD

**Issue by fervi** [IsmAvatar/LateralGM#369] opened 2018-03-21 11:52 UTC
Well, new Debian has new version of Java. On this version LGM doesn't work and I manually change Java to 8.

Log:
http://meshnet-users.tk/paste/p/hoqm/l.txt

**Comment by JoshDreamland** [comment] 2018-03-21 12:21
They must have finally removed that junk splash screen. It used to cause horrifying X bugs.

Is this the official Oracle JVM, or OpenJRE? If it's the latter, can you try it in the official Java 9 JRE?

**Comment by fervi** [comment] 2018-03-21 12:31
OpenJDK. I can try (I think) Oracle JVM, give me few minutes (or hours :D)

**Comment by RobertBColton** [comment] 2018-03-21 22:56
@fervi What LGM version? Did you download one of the newest ones I recently made? Those have Java 9 fixes:
https://github.com/IsmAvatar/LateralGM/releases

Otherwise your issue does look like a duplicate of #227, we are all already aware of how buggy the OpenJDK is.

**Comment by fervi** [comment] 2018-03-22 10:48
@RobertBColton On 1.8.40 doesn't work. [I usually test Enigma's LateralGM]
Of course (as I said) it works on older version OpenJDK (8) and newer (11). So maybe only 9 version is bugged (and we can report that on Enigma & LGM wiki)

Oracle JVM works (noooo, FLOSS must be master race :P)

If you want to close - do it, or no

**Comment by RobertBColton** [comment] 2019-04-16 01:14
@fervi Sorry it took me so long to get back to this. What you said is correct, because of what you said I would just consider in an OpenJDK 9 regression since it works in OpenJDK 8 and 11 as well as Oracle JDK 9. We can in fact close this and amend it to #227 chalking it up as yet another OpenJDK bug. ☹️

**Closed by RobertBColton** 2019-04-16 01:14 UTC
Labels: Error, JDK, Platform/System
