### ISSUE TITLE
Null pointer when saving

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#297] opened 2016-05-28 11:12 UTC
1. Rename sprite to one that already exists and has references to it  
2. Delete the old one  
3. Try to save  
4. Manually rebuild your GMX and be annoyed
```
Operating System: Linux
Version: 3.19.0-59-generic
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.7.0_101

Available processors (cores): 4
Free memory (bytes): 104752576
Maximum memory (bytes): 620756992
Total memory available to JVM (bytes): 164102144

File system root: /
Total space (bytes): 28875468800
Free space (bytes): 7139553280
Usable space (bytes): 5649129472

Stack trace:
org.lateralgm.file.GmFormatException: java.lang.NullPointerException: null
	at org.lateralgm.file.GMXFileWriter.iterateGmObjects(GMXFileWriter.java:1356)
	at org.lateralgm.file.GMXFileWriter.writeGmObjects(GMXFileWriter.java:1475)
	at org.lateralgm.file.GMXFileWriter.writeProjectFile(GMXFileWriter.java:185)
	at org.lateralgm.main.FileChooser$ProjectWriter.write(FileChooser.java:409)
	at org.lateralgm.main.FileChooser$2.run(FileChooser.java:745)
	at java.lang.Thread.run(Thread.java:745)

java.net.UnknownServiceException: protocol doesn't support output
	at java.net.URLConnection.getOutputStream(URLConnection.java:852)
	at org.lateralgm.main.FileChooser$2.run(FileChooser.java:771)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by RobertBColton** [comment] 2016-05-29 20:47
I can confirm that I am able to reproduce this with the GMX format only, the GMK format seems to be fine. It seems to occur regardless of whether the object frame is left open or not.

To clarify the steps to reproduce with an empty project:
1) Create two sprites
2) Create an object and assign it the first sprite
3) Rename the second object to the first sprite, i.e. rename "spr_1" to "spr_0"
4) Delete the original "spr_0"
5) Try to save as GMX and it will throw the exception. Save as a GMK and it will not throw the exception.

**Comment by RobertBColton** [comment] 2016-05-31 03:52
Alright, I've attempted fixing this in #300 and I have made a new release available.
https://github.com/IsmAvatar/LateralGM/releases

The fix makes the GMX writer behave the same as the GMK one does, it should safely dereference the resource references now. Please let me know if you have anymore problems.

**Closed by RobertBColton** 2016-05-31 03:52 UTC
Labels: Bug, Confirmed, File Writer, Reproducible

**Comment by RobertBColton** [comment] 2020-08-20 22:42
This was also somewhat related to #122 as deleting the sprite should have cleared the reference automatically
