### ISSUE TITLE
LateralGM crashes on load screen

### ISSUE THREAD

**Issue by JamesF22293** [IsmAvatar/LateralGM#379] opened 2018-08-17 15:05 UTC
Here is the error report:

LateralGM Version: 1.8.40

Operating System: Windows 10
Version: 10.0
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_181

Available processors (cores): 8
Free memory (bytes): 3045760
Maximum memory (bytes): 259522560
Total memory available to JVM (bytes): 16252928

File system root: C:\
Total space (bytes): 243119681536
Free space (bytes): 126678081536
Usable space (bytes): 126678081536

File system root: D:\
Total space (bytes): 11616120832
Free space (bytes): 1200005120
Usable space (bytes): 1200005120

Stack trace:
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\James\Downloads\papyrus.gmk
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.lateralgm.components.GmMenuBar.updateRecentFiles(GmMenuBar.java:86)
	at org.lateralgm.components.GmMenuBar.<init>(GmMenuBar.java:139)
	at org.lateralgm.main.LGM.main(LGM.java:1138)

java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(Unknown Source)
	at java.awt.SplashScreen.update(Unknown Source)
	at org.lateralgm.main.LGM$SplashProgress.update(LGM.java:1440)
	at org.lateralgm.main.LGM$SplashProgress.progress(LGM.java:1433)
	at org.lateralgm.main.LGM.main(LGM.java:1140)

**Comment by RobertBColton** [comment] 2019-04-16 00:26
I've seen this issue a couple of times now but cannot reproduce. Please try to provide steps for me to reproduce it so I can understand how `C:\Users\James\Downloads\papyrus.gmk` ended up in your recent files list. Closing as a duplicate of #376.

**Closed by RobertBColton** 2019-04-16 00:26 UTC
Labels: Error
