### ISSUE TITLE
Cannot load a GMS project

### ISSUE THREAD

**Issue by OpravdovyKvejk** [IsmAvatar/LateralGM#311] opened 2016-09-28 15:03 UTC
Trying to open my friend's GMS project, getting the following error:

Error report:

```
Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_101

Available processors (cores): 2
Free memory (bytes): 163125048
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259588096

File system root: C:\
Total space (bytes): 536763953152
Free space (bytes): 516821135360
Usable space (bytes): 516821135360

File system root: D:\
Total space (bytes): 6208972800
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
org.lateralgm.file.GmFormatException: javax.imageio.IIOException: I/O error reading PNG header!
    at com.sun.imageio.plugins.png.PNGImageReader.readHeader(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at org.lateralgm.file.GMXFileReader.iterateSprites(GMXFileReader.java:599)
    at org.lateralgm.file.GMXFileReader.iterateSprites(GMXFileReader.java:537)
    at org.lateralgm.file.GMXFileReader.iterateSprites(GMXFileReader.java:537)
    at org.lateralgm.file.GMXFileReader.readSprites(GMXFileReader.java:624)
    at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:246)
    at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:200)
    at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
    at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by RobertBColton** [comment] 2016-09-28 17:42
Can you tell me, after you close the error, what is the last sprite/background loaded? I would take a look at the GMX file and see what comes right after that sprite/background in the tree. The error is clearly from reading a corrupt PNG file or one that is not supported by your JVM (seems unlikely because it's the Oracle JVM and I've never seen anybody report this error before). There's not much else I can help without you providing a game that reproduces it or giving me some more details.

**Comment by lofcz** [comment] 2016-09-29 16:42
@RobertBColton Here's the link: [repository](https://github.com/lofcz/SimplexRpgEngine)
Also, please, take a look at this conversation: [issue](https://github.com/lofcz/SimplexRpgEngine/issues/17)
Is there such a limitation in LateralGM? 
Thanks for your time.

**Comment by RobertBColton** [comment] 2016-09-29 16:49
Can you give me a direct download to the GMX? I don't mean to be rude but I am having a hard time finding it here because I don't speak this language that you guys do.

Anyway, no there should be no such limit in LGM. Nobody has done any benchmarking before but the only limit would be whatever can fit in your RAM, obviously this is a lot less than if LGM were a native application though.

**Comment by lofcz** [comment] 2016-09-29 16:54
@RobertBColton Oh, I am sorry, my bad. Here you go: [link](https://github.com/lofcz/SimplexRpgEngine/archive/master.zip)
Path is DragonRise3/Engine source/DragonRise3.project.gmx

**Comment by RobertBColton** [comment] 2016-09-29 17:07
The problem is the file sCoinAnimated_54.png which is the 54th subimage of the sCoinAnimated sprite. It's corrupted and even Windows explorer is not able to display it.

![Corrupted Subframe](https://cloud.githubusercontent.com/assets/3212801/18964021/26eac6ec-8645-11e6-96dc-e488cfe11de5.png)

After correcting that locally myself, LGM is able to load the whole project.
![LGM Loading RPG Engine](https://cloud.githubusercontent.com/assets/3212801/18964145/9e08a1fe-8645-11e6-9d47-e0a1f69551db.png)


So I am going to close this then since it was not an LGM issue. However, in cases like this I think LGM should probably print out the file name when it hits an I/O error. Maybe I will keep this open to scope for that.

**Comment by lofcz** [comment] 2016-09-29 17:11
Oh, that was pretty silly, sorry for bothering you. One more question, scripts loaded fine? As we are using script tabs and I've just seen #307. I am going to repair corrupted file anyway.

**Comment by OpravdovyKvejk** [comment] 2016-09-29 17:16
Thank you. Printing out the file name would be a neat feature.

**Comment by RobertBColton** [comment] 2016-09-29 17:22
The scripts seem to open fine but ``#define`` is not handled because of #307. I'm the one who wrote the GMX stuff for LGM and I just never got around to it. I remembered when they added tabbed scripts and I thought it was silly they did that because it was not necessary at all. But I digress, maybe if I find time I can add some experimental support for #307 by making it split them into separate scripts. I can do that temporarily to make games run without having to revamp the whole UI. There's some other really small bugs that crept up like #304 that I can fix real easily. So maybe I'll give another update here soon.

**Comment by OpravdovyKvejk** [comment] 2016-09-29 17:41
Also, allowing users to use their code editor of choice would be great, because the code editor in LGM is really basic and barebones. But that's for another time.

**Comment by RobertBColton** [comment] 2018-01-08 11:53
I am closing this as resolved because the latest version of LGM has all of the above features mentioned. This includes showing the file name in error messages for the GMX reader, splitting and loading all scripts that are tabbed in GMX, and configuring an external script editor. I know these settings work they were just never documented. You can find the option to configure an external editor under File->Preferences->External editor. All you need to do is enter a command using this documented format:
https://enigma-dev.org/docs/Wiki/Overriding_settings#Settings_List

We can look at improving the UI for all of this later. If you have any new issues, please post separate tickets. Thanks!

**Closed by RobertBColton** 2018-01-08 11:53 UTC
Labels: Confirmed, Error, Feedback Needed, File Reader, Reproducible, Task, Tweak
