### ISSUE TITLE
When event actions are copy and pasted - if you edit one it edits all copies.

### ISSUE THREAD

**Issue by jbskaggs42** [IsmAvatar/LateralGM#380] opened 2018-08-24 15:08 UTC
LateralGM:
have this weird thing happening. If I copy a code action  from one event to another event, then any edits to either copy of the  code action changes both copies.

**Comment by RobertBColton** [comment] 2019-01-05 09:34
Thanks for the report!

You are correct about this, it's easily reproducible. Ok, so the issue is because the actions are being shallow copied. This is an annoying work around, but it is fixed if you save the project then reload it from the recent files list.

Please understand that LateralGM is currently not being developed and I have shifted development effort to RadialGM. I will leave this ticket open for you in case someone else picks up development of LGM.

**Comment by RobertBColton** [comment] 2019-04-14 18:59
Ok, I did some more research into this issue and what I said was correct. It is because the context menu actions do a shallow clone of the actions. If you use the keyboard shortcuts instead of right clicking this does not occur and a deep copy is performed. The reason is because the keyboard shortcuts are provided by Java and are just extended out of the drag and drop support. I also see that performing a drag and drop while holding CTRL+C (which means copy drag and drop) will perform a correct deep copy.

**Comment by RobertBColton** [comment] 2019-04-14 19:32
Closing as resolved by #392. You can download a new release of version 1.8.43 which contains these fixes.
https://github.com/IsmAvatar/LateralGM/releases/tag/v1.8.43

**Closed by RobertBColton** 2019-04-14 19:32 UTC
Labels: Bug, Confirmed, Drag and Drop, Reproducible
