### ISSUE TITLE
Illegal Character in Opaque Part  at Index 2

### ISSUE THREAD

**Issue by NrdShmN** [IsmAvatar/LateralGM#442] opened 2019-06-14 15:59 UTC
LateralGM Version: 1.8.82
Working Directory: C:\Users\MicahlDickens\enigma-dev\lateralgm.jar

Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_211

Available processors (cores): 12
Free memory (bytes): 93069832
Maximum memory (bytes): 1862270976
Total memory available to JVM (bytes): 126877696

File system root: C:\
Total space (bytes): 254876315648
Free space (bytes): 54281424896
Usable space (bytes): 54281424896

Stack trace:
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\MicahlDickens\Documents\WGS\OneDrive\WeaponsGradeStudios\Video Games\Evolver\Evolver.gmx\Evolver.project.gmx
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.lateralgm.components.GmMenuBar.updateRecentFiles(GmMenuBar.java:86)
	at org.lateralgm.components.GmMenuBar.<init>(GmMenuBar.java:139)
	at org.lateralgm.main.LGM.main(LGM.java:1130)

java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(Unknown Source)
	at java.awt.SplashScreen.update(Unknown Source)
	at org.lateralgm.main.LGM$SplashProgress.update(LGM.java:1432)
	at org.lateralgm.main.LGM$SplashProgress.progress(LGM.java:1425)
	at org.lateralgm.main.LGM.main(LGM.java:1132)

**Comment by RobertBColton** [comment] 2019-07-07 05:57
Hi, this error keeps being reported a lot but I haven't been able to consistently reproduce it. I have to close your ticket since it is a duplicate of #376 and provides no new information. The workaround is to clear your recent files list, either by resetting the preferences, or manually remove the key store for LGM from the Windows Registry.

If you find a consistent way of reproducing the bug, please share it with me so I can get this fixed. Again, you can see in #376 I've tried various ways of reproducing it but can't seem to.

Thank you.

**Closed by RobertBColton** 2019-07-07 05:57 UTC

**Comment by RobertBColton** [comment] 2019-07-07 06:01
Also, I am beginning to think the bug may be caused when people are updating from older version of LGM. If you had previously used another older version of LGM, please state which version that was. If the above workaround I mentioned also doesn't work, try opening the older LGM to reset the preferences which clears the recent files list.

**Comment by RobertBColton** [comment] 2019-07-08 09:20
From the people experiencing this, if you would like to help in getting it fixed, I need answers to these questions from a few people.

1) What were you doing when the exception occurred?
2) Is this the first time you used LateralGM?
3) Were you using LateralGM by itself or in combination with ENIGMA?
4) Were you or have you ever opened a file by dragging and dropping it onto LGM or passing it from the command line?
5) How do you normally open files in LateralGM?
