### ISSUE TITLE
Error opening script editor/IBM JDK

### ISSUE THREAD

**Issue by Salabasama** [IsmAvatar/LateralGM#459] opened 2019-10-18 00:57 UTC
LateralGM Version: 1.8.85
Working Directory: /home/mustafa/enigma-dev/lateralgm.jar

Operating System: Linux
Version: 4.15.0-54-generic
Architecture: amd64

Java Name: IBM J9 VM
Java Vendor: IBM Corporation
Version: 1.8.0_211

Available processors (cores): 8
Free memory (bytes): 5800920
Maximum memory (bytes): 536870912
Total memory available to JVM (bytes): 24641536

File system root: /
Total space (bytes): 117610516480
Free space (bytes): 92235096064
Usable space (bytes): 86216691712

Stack trace:
java.lang.NullPointerException
	at org.lateralgm.components.CodeTextArea.setupKeywords(CodeTextArea.java:295)
	at org.lateralgm.components.CodeTextArea.<init>(CodeTextArea.java:130)
	at org.lateralgm.subframes.ActionFrame.<init>(ActionFrame.java:172)
	at org.lateralgm.subframes.ActionFrame.<init>(ActionFrame.java:89)
	at org.lateralgm.components.ActionList.openActionFrame(ActionList.java:236)
	at org.lateralgm.subframes.GmObjectFrame.editSelectedEvent(GmObjectFrame.java:972)
	at org.lateralgm.subframes.GmObjectFrame.access$0(GmObjectFrame.java:944)
	at org.lateralgm.subframes.GmObjectFrame$2.mousePressed(GmObjectFrame.java:835)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:291)
	at java.awt.Component.processMouseEvent(Component.java:6547)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3335)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2250)
	at java.awt.Component.dispatchEventImpl(Component.java:4900)
	at java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.awt.Component.dispatchEvent(Component.java:4722)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4915)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4487)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2757)
	at java.awt.Component.dispatchEvent(Component.java:4722)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.awt.EventQueue.access$500(EventQueue.java:108)
	at java.awt.EventQueue$3.run(EventQueue.java:720)
	at java.awt.EventQueue$3.run(EventQueue.java:714)
	at java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.awt.EventQueue$4.run(EventQueue.java:744)
	at java.awt.EventQueue$4.run(EventQueue.java:742)
	at java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:216)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:127)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:112)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:104)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:93)

**Comment by RobertBColton** [comment] 2019-10-24 00:37
This is an interesting one I can't reproduce on that version. I've never seen the IBM JVM before. Is this related to a specific project at all or just opening up a brand new script at start?

**Comment by JoshDreamland** [comment] 2019-10-24 01:19
The exception traces to [`CodeTextArea.java:295`](https://github.com/IsmAvatar/LateralGM/blob/master/org/lateralgm/components/CodeTextArea.java#L295). Odds are, it's talking about the token marker being null, which would imply that the cache missed and the language wasn't recognized. You could add logging for when that happens to get more information.

In general, even if we can't understand why a variable came to be null, we can add handling for it.

**Comment by RobertBColton** [comment] 2019-10-24 02:02
Given that it's IBM, I assume escalated security restrictions are the JVM default, which may be interfering with reflection used to load the class.

**Comment by JoshDreamland** [comment] 2019-10-24 02:22
Good theory. Can we use providers to remove the need for reflection?

**Comment by Salabasama** [comment] 2019-11-14 20:40
> This is an interesting one I can't reproduce on that version. I've never seen the IBM JVM before. Is this related to a specific project at all or just opening up a brand new script at start?

New script, just after opening.  Some variant of the NPE comes up for other actions as well.

**Comment by RobertBColton** [comment] 2019-11-14 20:56
I really want to blame the IBM JVM here. Is it possible for you to try OpenJDK, or more preferably, Oracle JDK?

**Comment by Salabasama** [comment] 2019-11-14 21:24
I'll look into it.  Hopefully that's just my issue.

**Comment by Salabasama** [comment] 2019-11-15 05:12
Eventually managed to get back to OpenJDK.  Yes, I can run the script editor.  Happy to see "Compile failed at C++ level" again.

**Comment by RobertBColton** [comment] 2019-11-15 05:14
Yeah that takes the issue back to enigma-dev then, we can leave this open though as a reminder the IBM JDK has issues too. This is pretty much the case with any non-Oracle JDK.

**Comment by Salabasama** [comment] 2019-11-15 07:05
What version of Oracle JDK should I be using?  11?

**Comment by RobertBColton** [comment] 2019-11-15 20:03
Anything Java 7 or above that works, I am using Java 9 currently.
https://enigma-dev.org/download.htm

**Comment by Salabasama** [comment] 2019-11-20 21:03
I have installed 11.  Compile still fails at C++ level.  Relevant seeming section from the end of the log:

[g++] SHELLmain.cpp
Linking /tmp/egm15922487244366282234.tmp
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:168: recipe for target 'compile_game' failed
make[1]: *** [compile_game] Error 1
make[1]: Leaving directory '/home/mustafa/enigma-dev/ENIGMAsystem/SHELL'
Makefile:21: recipe for target 'Game' failed
make: *** [Game] Error 2

**Comment by RobertBColton** [comment] 2019-11-20 21:22
Yeah this part of the issue belongs on the ENIGMA tracker.
https://github.com/enigma-dev/enigma-dev/issues

But it seems very obvious you are just missing OpenGL. I recommend moving that part of your issue over to the other tracker and then answering me if you installed all the deps correctly in MSYS2?
https://enigma-dev.org/docs/Wiki/Install:Windows#-_Step_2:_Install_Dependencies

**Comment by RobertBColton** [comment] 2020-07-20 04:59
Closing as resolved by 581b4e39b2919784fe9e10ffe5cdcc6d2c6c2bfe and you can download the latest v1.8.159 release which should allow you to open the code editor under other JDKs. I hope this helps! If you still have problems feel free to post a new issue.

**Closed by RobertBColton** 2020-07-20 04:59 UTC
Labels: Confirmed, Error, JDK
