### ISSUE TITLE
Enigma - Clean rooms in EGM

### ISSUE THREAD

**Issue by fervi** [IsmAvatar/LateralGM#79] opened 2013-07-09 14:04 UTC
Hello!

Ok, let's start
When I create my project in 25.04.2013 - everybody works (you know, old version of LGM etc.)
When I try to run this project yesterday (8.07.2013) - Project works propertly, except empty rooms.

http://enigma-dev.org/forums/index.php?topic=1346.0

Now I'm using Debian, but when I creating project, it was Xubuntu

**Comment by RobertBColton** [comment] 2015-11-17 13:59
Another user may have reproduced this issue, can not confirm until they provide additional details.
http://enigma-dev.org/forums/index.php?topic=2612

**Comment by RobertBColton** [comment] 2020-07-12 15:46
The real reason this happened is because like GMX in #323, EGM is not being considered in the push backups mechanism. Perhaps we need to consider making the backups mechanism more pluggable and delegating to the file writers/flavors so that it's automatically handled.

**Comment by RobertBColton** [comment] 2020-07-18 04:51
Closing as I've moved the issue to the lgmplugin where it belongs.
https://github.com/enigma-dev/lgmplugin/issues/79

I've posted a separate issue regarding the modularization of the backups mechanism.
https://github.com/IsmAvatar/LateralGM/issues/517

**Closed by RobertBColton** 2020-07-18 04:51 UTC
Labels: Bug, File Reader, File Writer, Pertinent

**Comment by RobertBColton** [comment] 2020-07-18 06:55
I actually ended up tracking down the real cause of fervi's specific issue with his game.
https://github.com/enigma-dev/lgmplugin/issues/79

It was in fact a regression caused by forthevin's insertion of the room caption into the binary part of the EGM room format.
https://github.com/enigma-dev/enigma-dev/commit/56d6e87007aba474c94fd62df448dbfb85e0ee6c

As I said in the lgmplugin issue, I have a way of opening the game up if @fervi is still interested in retrieving it. I can actually convert it to GMK, GMX, or some other better supported and stable format if he would like.
