### ISSUE TITLE
Saving gmx audio files appears to not work properly.

### ISSUE THREAD

**Issue by SuperRiderTH** [IsmAvatar/LateralGM#361] opened 2018-03-15 19:43 UTC
Upon saving a gmx, it spits out the audio files like so.

![image](https://user-images.githubusercontent.com/5368844/37487224-4a082668-2867-11e8-89f5-e89deae39416.png)

**Comment by RobertBColton** [comment] 2018-03-15 19:49
Looks like a regression, give me a few minutes to fix it.

**Comment by RobertBColton** [comment] 2018-03-15 19:53
Bleh, I just tried a couple of things, including saving the Mark Overmars FPS game as a GMX, closing and reopening then saving again. Starting a new project, new sound loaded from disk, save twice, close and reopen. I can't reproduce it on Windows 10. I'm testing with the latest 1.8.39 release I made:
https://github.com/IsmAvatar/LateralGM/releases

What LGM version were you using? Can you tell me how to reproduce it?

**Comment by SuperRiderTH** [comment] 2018-03-15 19:55
I'm using 1.8.39 on Ubuntu. All I did was open a GMX and save it.
![image](https://user-images.githubusercontent.com/5368844/37487853-3547f8dc-2869-11e8-8cdb-2e6d2cc0a578.png)

**Comment by RobertBColton** [comment] 2018-03-15 19:56
Oh I see what happened, Linux doesn't like the backslash. This was caused by #353 where I changed the utility method and the new one doesn't convert the path to POSIX. Easy fix, I'll just have to update the GMX reader/writer that calls that utility method.

**Closed** 2018-03-15 20:36 UTC
