### ISSUE TITLE
Room Editor Error With Negative X-scale

### ISSUE THREAD

**Issue by BeepBoop486** [IsmAvatar/LateralGM#460] opened 2019-10-18 19:39 UTC
LateralGM Version: 1.8.89
Working Directory: /home/mya/enigma-dev/lateralgm.jar

Operating System: Linux
Version: 4.19.0-6-amd64
Architecture: amd64

Java Name: OpenJDK 64-Bit Server VM
Java Vendor: Debian
Version: 11.0.4

Current Thread: AWT-EventQueue-0
Available processors (cores): 2
Free memory (bytes): 31481856
Maximum memory (bytes): 1000341504
Total memory available to JVM (bytes): 907018240

File system root: /
Total space (bytes): 29394636800
Free space (bytes): 19457949696
Usable space (bytes): 17941184512

Stack trace:
java.lang.NegativeArraySizeException: -2
	at org.lateralgm.util.BinPlane$Candidate.setBounds(BinPlane.java:380)
	at org.lateralgm.ui.swing.visuals.BinVisual.setBounds(BinVisual.java:99)
	at org.lateralgm.ui.swing.visuals.BinVisual.setBounds(BinVisual.java:86)
	at org.lateralgm.ui.swing.visuals.VisualBox.setBounds(VisualBox.java:30)
	at org.lateralgm.ui.swing.visuals.RoomVisual$InstanceVisual.validate(RoomVisual.java:841)
	at org.lateralgm.ui.swing.visuals.RoomVisual$InstanceVisual.<init>(RoomVisual.java:753)
	at org.lateralgm.ui.swing.visuals.RoomVisual$InstanceVisualListManager.createVisual(RoomVisual.java:1112)
	at org.lateralgm.ui.swing.visuals.RoomVisual$InstanceVisualListManager.createVisual(RoomVisual.java:1)
	at org.lateralgm.ui.swing.visuals.RoomVisual$VisualListManager.<init>(RoomVisual.java:1152)
	at org.lateralgm.ui.swing.visuals.RoomVisual$InstanceVisualListManager.<init>(RoomVisual.java:1106)
	at org.lateralgm.ui.swing.visuals.RoomVisual.<init>(RoomVisual.java:124)
	at org.lateralgm.components.visual.RoomEditor.<init>(RoomEditor.java:161)
	at org.lateralgm.subframes.RoomFrame.<init>(RoomFrame.java:1925)
	at org.lateralgm.subframes.ResourceFrame$DefaultResourceFrameFactory.makeFrame(ResourceFrame.java:116)
	at org.lateralgm.components.impl.ResNode.openFrame(ResNode.java:223)
	at org.lateralgm.components.impl.ResNode.openFrame(ResNode.java:207)
	at org.lateralgm.main.Listener$MListener.mouseReleased(Listener.java:930)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by RobertBColton** [comment] 2019-10-24 00:38
Interesting, I'll check it out later.

**Comment by RobertBColton** [comment] 2019-10-24 23:21
This is quite interesting, and odd that this issue has not been raised before. I assume it to be related to a specific project file which may be corrupted possibly. Do you get this every time or just with a specific project? If a specific project, could you please attach it in a reply here?

Otherwise it will be easiest to fix if we can get steps to reproduce the bug. All I need is steps to reproduce it on my end to be able to find a fix.

**Comment by BeepBoop486** [comment] 2019-10-25 00:45
It's cuz the xscale of an object is - 1

**Comment by RobertBColton** [comment] 2019-10-25 00:53
Hrm, I tested this out, making a GMX in GMS and loading it up in LGM. I could not reproduce it. Can you share additional details of how to reproduce?

![LGM GMX Negative xscale](https://user-images.githubusercontent.com/3212801/67535375-412a4400-f6a0-11e9-9fb9-ccdb908d1431.png)

**Comment by BeepBoop486** [comment] 2019-10-25 01:04
When I try to do that in the IDE it appears to return an error or... Just doesn't work. Would you like that I share the gmx of the room?

**Comment by RobertBColton** [comment] 2019-10-25 01:51
If you like, GitHub allows you to upload directly to your reply (which is better because then it's here for future maintainers). Now, I can see that LGM does not accept negative xscales since you mention it. However, I still can't reproduce the error. Can you explain more specific steps to reproduce the error.

**Comment by BeepBoop486** [comment] 2019-10-27 00:39
This is the room (I can't upload .gmx files so i've copy-pasted the room xd)

<room>
  <caption></caption>
  <width>1872</width>
  <height>1056</height>
  <vsnap>1</vsnap>
  <hsnap>1</hsnap>
  <isometric>0</isometric>
  <speed>60</speed>
  <persistent>0</persistent>
  <colour>8421504</colour>
  <showcolour>-1</showcolour>
  <code>global.cube = 1;
global.nave = 0;
global.ball = 0;
global.ufo = 0;
global.wave = 0;    
global.robot = 0;
global.spider = 0;
global.swing = 0;
global.voider = 0;
global.jetpak = 0;
global.trail = 0;
global.death = 0;
global.particle = 0;

global.negrito = 0;
instance_create(0,0,obj_negro);
blu2=make_colour_rgb(2,97,255)
background_blend[0]=c_blue;
background_blend[1]=c_blue;
if !audio_is_playing(s_menu){
audio_play_sound(s_menu,1,true);}</code>
  <enableViews>-1</enableViews>
  <clearViewBackground>-1</clearViewBackground>
  <clearDisplayBuffer>-1</clearDisplayBuffer>
  <makerSettings>
    <isSet>0</isSet>
    <w>0</w>
    <h>0</h>
    <showGrid>0</showGrid>
    <showObjects>0</showObjects>
    <showTiles>0</showTiles>
    <showBackgrounds>0</showBackgrounds>
    <showForegrounds>0</showForegrounds>
    <showViews>0</showViews>
    <deleteUnderlyingObj>0</deleteUnderlyingObj>
    <deleteUnderlyingTiles>0</deleteUnderlyingTiles>
    <page>0</page>
    <xoffset>0</xoffset>
    <yoffset>0</yoffset>
  </makerSettings>
  <backgrounds>
    <background visible="0" foreground="0" name="background2" x="0" y="0" htiled="-1" vtiled="-1" hspeed="-2" vspeed="0" stretch="0"/>
    <background visible="0" foreground="0" name="" x="0" y="775" htiled="-1" vtiled="0" hspeed="-18" vspeed="0" stretch="0"/>
    <background visible="-1" foreground="0" name="background2" x="0" y="0" htiled="0" vtiled="0" hspeed="0" vspeed="0" stretch="0"/>
    <background visible="0" foreground="0" name="" x="0" y="0" htiled="-1" vtiled="-1" hspeed="0" vspeed="0" stretch="0"/>
    <background visible="0" foreground="0" name="" x="0" y="0" htiled="-1" vtiled="-1" hspeed="0" vspeed="0" stretch="0"/>
    <background visible="0" foreground="0" name="" x="0" y="0" htiled="-1" vtiled="-1" hspeed="0" vspeed="0" stretch="0"/>
    <background visible="0" foreground="0" name="" x="0" y="0" htiled="-1" vtiled="-1" hspeed="0" vspeed="0" stretch="0"/>
    <background visible="0" foreground="0" name="" x="0" y="0" htiled="-1" vtiled="-1" hspeed="0" vspeed="0" stretch="0"/>
  </backgrounds>
  <views>
    <view visible="-1" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1872" hview="1056" xport="0" yport="0" wport="1872" hport="1056" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
    <view visible="0" objName="&lt;undefined&gt;" xview="0" yview="0" wview="1024" hview="768" xport="0" yport="0" wport="1024" hport="768" hborder="32" vborder="32" hspeed="-1" vspeed="-1"/>
  </views>
  <instances>
    <instance objName="obj_select_icon" x="1475" y="745" name="inst_368CA5F6" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1377" y="745" name="inst_CAE5D46B" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1279" y="745" name="inst_6D7FE09E" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_preview_c1" x="937" y="279" name="inst_98EB1134" locked="0" code="" scaleX="1.64999997615814" scaleY="1.64999997615814" colour="4278255424" rotation="0"/>
    <instance objName="obj_npageicon" x="1658" y="648" name="inst_9E6AA1D6" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_bpageicon" x="213" y="648" name="inst_217F7EFC" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_bmenu" x="82" y="78" name="inst_E8AAAD78" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_mdetail_1" x="0" y="0" name="inst_7BE63F0C" locked="0" code="" scaleX="-1" scaleY="-1" colour="4294967295" rotation="0"/>
    <instance objName="obj_npagecolor" x="1593" y="936" name="inst_78B8BD8C" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_bolitacolor" x="338" y="1019" name="inst_22BF4113" locked="0" code="" scaleX="0.5" scaleY="0.5" colour="4294967295" rotation="0"/>
    <instance objName="obj_bolitacolor" x="338" y="859" name="inst_D47AA5DF" locked="0" code="" scaleX="0.5" scaleY="0.5" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1480" y="855" name="inst_12B722E9" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1480" y="936" name="inst_09B67268" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1480" y="1016" name="inst_A1CE9D5C" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1382" y="1016" name="inst_561DBCF4" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1382" y="936" name="inst_25E1D979" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1382" y="855" name="inst_5DDAC0EC" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1284" y="855" name="inst_DD88DB8A" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1284" y="936" name="inst_017C2858" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1284" y="1016" name="inst_C908C05C" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1186" y="1016" name="inst_FB9791B6" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1186" y="936" name="inst_15F8A658" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1186" y="855" name="inst_13744820" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1088" y="855" name="inst_691B4CE1" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1088" y="936" name="inst_DE6C0C95" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="1088" y="1016" name="inst_DED8A2AC" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="990" y="1016" name="inst_64D4C7F3" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="990" y="936" name="inst_7CD6176B" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="990" y="855" name="inst_A1BA7A83" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="892" y="855" name="inst_7B4CD249" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="892" y="936" name="inst_6A743E4A" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="892" y="1016" name="inst_DD53AC41" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="794" y="1016" name="inst_1DFB1600" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="794" y="936" name="inst_F30427A0" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="794" y="855" name="inst_BDF701A4" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="696" y="855" name="inst_98022F76" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="696" y="936" name="inst_C86E4622" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="696" y="1016" name="inst_3675927C" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="598" y="1016" name="inst_FEF4FB7B" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="598" y="936" name="inst_3F664F1F" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="598" y="855" name="inst_FAFA3E1E" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="500" y="855" name="inst_2F631366" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="500" y="936" name="inst_04A727EE" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="500" y="1016" name="inst_2B702BB6" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="402" y="1016" name="inst_D0C925B4" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="402" y="855" name="inst_0BBD44D2" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_bpagecolor" x="278" y="937" name="inst_EE64D9A7" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectcolor" x="402" y="936" name="inst_4F349C68" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_bolitacolor" x="1573" y="859" name="inst_916B2E91" locked="0" code="" scaleX="0.5" scaleY="0.5" colour="4294967295" rotation="0"/>
    <instance objName="obj_bolitacolor" x="1573" y="1019" name="inst_540A89C1" locked="0" code="" scaleX="0.5" scaleY="0.5" colour="4294967295" rotation="0"/>
    <instance objName="obj_chage_glow" x="127" y="926" name="inst_5C1D0B5E" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_glowoption" x="127" y="992" name="inst_F30D3C05" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="1620" y="425" name="inst_6893208E" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_mdetail_1" x="0" y="0" name="inst_E310FC83" locked="0" code="" scaleX="1" scaleY="-1" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="1506" y="425" name="inst_107B62AC" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="1164" y="425" name="inst_FAB44992" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="1278" y="425" name="inst_1516DDBC" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="1050" y="425" name="inst_294CA39F" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="252" y="425" name="inst_A144D5BB" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="366" y="425" name="inst_50CE2455" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="480" y="425" name="inst_AC299C70" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="594" y="425" name="inst_3FA49001" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="936" y="425" name="inst_C86DACBD" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="822" y="425" name="inst_4D58DBAE" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="708" y="425" name="inst_4BE279A2" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_selectmrds" x="1392" y="425" name="inst_E4D2B55C" locked="0" code="" scaleX="0.850000023841858" scaleY="0.850000023841858" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1181" y="745" name="inst_9F30D954" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1083" y="745" name="inst_F68E8A5F" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="985" y="745" name="inst_86C9A388" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="887" y="745" name="inst_A12058FF" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="789" y="745" name="inst_217E2B0E" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="691" y="745" name="inst_6AD2480A" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="593" y="745" name="inst_B9F09CD3" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="495" y="745" name="inst_2E0237E6" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="397" y="745" name="inst_1633DC3D" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="397" y="645" name="inst_A9241BD5" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="495" y="545" name="inst_B71A04AA" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="593" y="545" name="inst_5C70CA65" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="691" y="545" name="inst_24B52014" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="789" y="545" name="inst_EAE957DA" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="887" y="545" name="inst_1C8F19F3" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="985" y="545" name="inst_F2BA6406" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1083" y="545" name="inst_0FB63D2C" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1181" y="545" name="inst_39DF1FA4" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1279" y="545" name="inst_3546C991" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1377" y="545" name="inst_176E4277" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1475" y="545" name="inst_1AE49FC3" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="495" y="645" name="inst_F0AD3037" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="593" y="645" name="inst_275F46DD" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="691" y="645" name="inst_D7FC5D94" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="789" y="645" name="inst_A200C1F2" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="887" y="645" name="inst_1F906844" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="985" y="645" name="inst_9516D411" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1083" y="645" name="inst_53A6EF57" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1181" y="645" name="inst_181B44CF" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1279" y="645" name="inst_938DAB80" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1377" y="645" name="inst_E68D3050" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="1475" y="645" name="inst_B6FCA30A" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_select_icon" x="397" y="545" name="inst_D6A7580B" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_change_screen" x="1746" y="926" name="inst_BC884B2C" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_screenoption" x="1747" y="992" name="inst_C7075090" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/>
    <instance objName="obj_change_screen" x="1950" y="903" name="inst_3CF44F79" locked="0" code="" scaleX="1" scaleY="1" colour="33554431" rotation="0"/>
  </instances>
  <tiles/>
  <PhysicsWorld>0</PhysicsWorld>
  <PhysicsWorldTop>0</PhysicsWorldTop>
  <PhysicsWorldLeft>0</PhysicsWorldLeft>
  <PhysicsWorldRight>1024</PhysicsWorldRight>
  <PhysicsWorldBottom>768</PhysicsWorldBottom>
  <PhysicsWorldGravityX>0</PhysicsWorldGravityX>
  <PhysicsWorldGravityY>10</PhysicsWorldGravityY>
  <PhysicsWorldPixToMeters>0.100000001490116</PhysicsWorldPixToMeters>
</room>

**Comment by BeepBoop486** [comment] 2019-10-27 00:43
I can't upload the file or copy it, xd

**Comment by RobertBColton** [comment] 2019-10-28 19:47
That's fine, though I can tell you that putting it in a ZIP file will work.

**Comment by RobertBColton** [comment] 2019-10-28 20:12
Ok, minor correction, I am able to repro now that I made #462 to fix this. For me on Oracle JDK there is no exception, the instances just don't paint.

The reason is because the room's spatial hashing code wasn't programmed to handle negative dimensions.
https://github.com/IsmAvatar/LateralGM/blob/master/org/lateralgm/util/BinPlane.java#L380

I'm looking into it.

**Comment by RobertBColton** [comment] 2020-07-15 21:11
Closing this one as resolved by #462 that I just merged. You can download the latest 1.8.150 release which includes the desired functionality. I hope that you find this useful. Please note it's not supported for tiles yet which #515 has been opened to cover. Thanks again for reporting this!

**Closed by RobertBColton** 2020-07-15 21:11 UTC
Labels: Bug, Confirmed, Error, Reproducible
