### ISSUE TITLE
OpenJDK and Swing issues

### ISSUE THREAD

**Issue by rzhw** [IsmAvatar/LateralGM#227] opened 2015-10-31 11:20 UTC
Quick dump of issues from IRC. Repro'd on Ubuntu 15.10 with LGM 1.8.6.844.

With openjdk-8-jre:
- Set theme to Swing and select different items in the project tree or the Object frame events tree, the renderer will be screwed up. This does not occur with tree's that do not use a custom renderer. The same issues are visible in the tree of the default open dialog under this theme.
- Set theme to Swing and go to Help -> About, LGM will hang
- Set theme to Native and these will cause hangs (there may be others):
  - Open and Save dialog with JFileChooser will cause hang when navigating to a directory
  - Object editor will cause hang when adding an action

With openjdk-7-jre/openjdk-8-jre:
- Open progress dialog will stay on screen after open is done
- Save progress dialog will stay on screen after save if not already on screen, and will close after save if already on screen

To mitigate, install Oracle JRE.

**Comment by RobertBColton** [comment] 2015-11-01 01:53
I confirmed most of these issues with both OpenJDk 7/8 in my VirtualBox install of Ubuntu 15.1
Installing the proprietary Oracle JDK makes all of these issues go away. I am not really sure what all can be done since the about box for example is a simple JOptionPane call where we aren't doing anything at all special. The OpenJDK seems to be virtually unusable with Swing applications.

**Comment by faissaloo** [comment] 2016-06-16 07:59
>Do the save or load dialogs ever get stuck for you?  
  
No, I'm not getting any of the mentioned issues

**Comment by RobertBColton** [comment] 2016-06-16 08:03
@faissaloo What was the operating system, specific distro, and java -version again?

**Comment by faissaloo** [comment] 2016-06-16 08:31
@RobertBColton 

> java version "1.7.0_101"
>OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
>OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)  
  
GNU/Linux Xubuntu 14.04.4 LTS

**Comment by RobertBColton** [comment] 2016-06-16 08:42
Thanks!

**Comment by RobertBColton** [comment] 2019-04-16 01:18
Amending #369 to this as yet another OpenJDK regression. OpenJDK 9 has issues with LGM because of the splash screen which is a regression. The regression seems to have been fixed in OpenJDK 11 and does not exist in OpenJDK 8 or Oracle JDK 9.

**Closed** 2023-07-08 06:32 UTC
Labels: Reproducible, Bug, Error, Regression, Confirmed, Swing, JDK, Linux, Look and Feel, Drag and Drop
