### ISSUE TITLE
GMX/XML Control Characters

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#229] opened 2015-11-10 20:08 UTC
This file was created by LateralGM but LateralGM thinks that it is corrupted because some folders are missing (because they were not needed for the project) and so it does not load the room and on load two copies of the same path are loaded.
Here is the file: https://wakaba.dhcp.io:4433/102
(When you download it rename it to have the extension .7z, infotomb was down so I just used this)

**Comment by RobertBColton** [comment] 2015-11-10 20:17
I'll address this in 1.7, thank you for calling it to my attention. This will be easy to fix and I can get to it. Expect it fixed by Christmas if this release continues as planned.

**Comment by faissaloo** [comment] 2015-11-10 20:31
I did some debugging and it turns out the issue was actually with codes like &#0; being inserted into the saved xml files, not with an incomplete file

**Comment by RobertBColton** [comment] 2015-11-11 00:32
@faissaloo Oh great. Can you give me a specific piece of the XML to look at? I haven't run the test yet (doing school work) but would like to see it.

Also, for your own reference, at first I thought you were a bot. It was because of that link until I downloaded the file. FireFox wanted me to add a security exception. I'd recommend getting a free https://www.dropbox.com/ or Google Drive even Microsoft Cloud or w/e it is.

**Comment by faissaloo** [comment] 2015-11-11 08:48
Oh yeah sorry about that, I forgot that the SSL certificate for that site is self-signed. Anyways, the file that you should look at is in the objects folder (there's only one file in there)..

**Comment by RobertBColton** [comment] 2015-11-23 19:42
@faissaloo Alright I have reproduced the issue and you are correct. It is apparently related to the Java XML API's escaping of newline characters, why it is doing this I do not know.

Some of the code you entered into LGM:
```XML
            <string>path_add_point(path_0,10*&#0;53,room_height-(10*40),100)&#13;
path_add_point(path_0,10 *20,room_height-(10*3),100)&#13;
path_add_point(path_0,10*&#0;27,room_height-(10*27),100)&#13;
path_add_point(path_0,10*&#0;18,room_height-(10*16),100)&#13;
path_add_point(path_0,10*&#0;33,room_height-(10*46),100)&#13;
path_add_point(path_0,10*&#0;5,room_height-(10*21),100)&#13;
path_add_point(path_0,10*&#0;46,room_height-(10*44),100)&#13;
path_add_point(path_0,10*&#0;53,room_height-(10*5),100)&#13;
path_add_point(path_0,10*&#0;12,room_height-(10*53),100)&#13;
path_add_point(path_0,10*&#0;41,room_height-(10*4),100)&#13;
path_add_point(path_0,10*&#0;3,room_height-(10*31),100)&#13;
path_add_point(path_0,10*&#0;27,room_height-(10*20),100)&#13;
path_add_point(path_0,10*&#0;20,room_height-(10*27),100)&#13;
path_add_point(path_0,10*&#0;31,room_height-(10*9),100)</string>
```

Apparently the one in GM Studio does not escape newlines, judging by one of the example projects, but does still escape less than or equal signs, which is necessary to read the XML DOM elements. From the GMS cubes demo:
```XML
            <string>/// If we don't HAVE a cube model, create one.
if(global.cube&lt;0) CreateCube();


</string>
```

I can't see what is immediately causing the problem because creating a new LGM GMX project and entering the following into an object gets escaped and reloads fine. I will need some time to investigate a fix but I will surely find a solution for the next release.
LGM can read this fine:
```XML
            <string>/// If we don't HAVE a cube model, create one.
if(global.cube&lt;0) CreateCube();


</string>
```

**Comment by faissaloo** [comment] 2015-11-24 08:44
It happened because I did find and replace and accidentally copy and pasted a tab into the replace box, the editor didn't show any sign of there being a tab there so I wasn't even sure if it was there until I tried to save it.

**Comment by RobertBColton** [comment] 2015-11-24 10:35
@faissaloo Alrighty thank you very much. For now you may simply replace &#0; with "" or nothing using Notepad++ or something to get LGM or GMS to load the file again. Hopefully we can get this resolved in a future version, I am not sure of the best course of action at this point in time. It seems like JoshEdit needs a preference to treat the NULL character as a space or ignore it completely, as GMS's editor does.

**Comment by faissaloo** [comment] 2015-11-24 16:22
Ok, thank you :D

**Comment by RobertBColton** [comment] 2019-09-29 03:45
Here may be a solution: <https://stackoverflow.com/a/24739061>

**Comment by RobertBColton** [comment] 2020-07-19 22:16
Alright so this seems to be two different problems actually. Yes the XML escape sequences are invalid, but the issue is they shouldn't be there to begin with.

What I'm saying is that `&#0;` is the NUL character, NUL terminator in C++. The only way I could get one in the GMX was by hacking the writer like this. Basically, the XML transformer will only ever put `&#0;` in the case that a 0 byte is somewhere in the string it's transforming.
```java
byte[] lol = new byte[] { 0 };
argelement.appendChild(createElement(doc,"string",new String(lol,"UTF-8")));
byte[] lol = new byte[] { 0,0 };
argelement.appendChild(createElement(doc,"string",new String(lol,"UTF-16")));
char[] lol = new char[] { 0 };
argelement.appendChild(createElement(doc,"string",new String(lol)));
```

The GMX writer in LGM takes a regular old Java UTF-16 string and tells the transformer to write it as UTF-8. That's correct because all Java

**Closed** 2023-07-08 07:31 UTC
Labels: Reproducible, Error, Feedback Needed, Confirmed, File Reader, File Writer
