### ISSUE TITLE
disable egm

### ISSUE THREAD

**Issue by fundies** [IsmAvatar/LateralGM#444] opened 2019-06-29 08:53 UTC
should probably disable egm saving / loading until its fixed

**Comment by RobertBColton** [comment] 2019-07-07 19:28
This belongs on ENIGMA's plugin tracker, has nothing to do with LGM. Also, it's a duplicate of an already outstanding issue.
https://github.com/enigma-dev/lgmplugin/issues/50

**Closed by RobertBColton** 2019-07-07 19:28 UTC
