### ISSUE TITLE
PropertyLinkFactory Disposal

### ISSUE THREAD

**Issue by JoshDreamland** [IsmAvatar/LateralGM#159] opened 2014-10-30 03:04 UTC
Occurred while typing a room caption:

```
Operating System: Linux
Version: 3.13.0-37-generic
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_65

Available processors (cores): 8
Free memory (bytes): 22801656
Maximum memory (bytes): 2792357888
Total memory available to JVM (bytes): 147324928

File system root: /
Total space (bytes): 176680636416
Free space (bytes): 30919041024
Usable space (bytes): 21920534528

Stack trace:
java.lang.IllegalStateException: Attempt to mutate in notification
    at javax.swing.text.AbstractDocument.writeLock(AbstractDocument.java:1338)
    at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:585)
    at org.lateralgm.ui.swing.propertylink.DocumentLink.setComponent(DocumentLink.java:37)
    at org.lateralgm.ui.swing.propertylink.DocumentLink.setComponent(DocumentLink.java:1)
    at org.lateralgm.util.PropertyLink.editComponent(PropertyLink.java:66)
    at org.lateralgm.util.PropertyLink.reset(PropertyLink.java:54)
    at org.lateralgm.util.PropertyLink.editProperty(PropertyLink.java:77)
    at org.lateralgm.ui.swing.propertylink.DocumentLink.update(DocumentLink.java:72)
    at org.lateralgm.ui.swing.propertylink.DocumentLink.insertUpdate(DocumentLink.java:60)
    at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:202)
    at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:749)
    at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:708)
    at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
    at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:670)
    at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1379)
    at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
    at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
    at javax.swing.JComponent.processKeyBinding(JComponent.java:2869)
    at javax.swing.JComponent.processKeyBindings(JComponent.java:2916)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
    at java.awt.Component.processEvent(Component.java:6293)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
    at java.awt.Component.dispatchEventImpl(Component.java:4742)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

This prevents the room caption from being saved.

I also have a probably-unrelated exception which occurred randomly while accidentally clicking (or right clicking?) somewhere on the screen (ostensibly in the room editor, as the trace suggests). My hand slipped, and I got this exception:

```
Operating System: Linux
Version: 3.13.0-37-generic
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_65

Available processors (cores): 8
Free memory (bytes): 56829688
Maximum memory (bytes): 2792357888
Total memory available to JVM (bytes): 151519232

File system root: /
Total space (bytes): 176680636416
Free space (bytes): 30951612416
Usable space (bytes): 21953105920

Stack trace:
java.lang.NullPointerException
    at org.lateralgm.subframes.RoomFrame.showSelectedInstance(RoomFrame.java:2039)
    at org.lateralgm.subframes.RoomFrame.access$4(RoomFrame.java:2018)
    at org.lateralgm.subframes.RoomFrame$3.mouseClicked(RoomFrame.java:452)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
    at java.awt.Component.processMouseEvent(Component.java:6519)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

This exception happened before the caption exception, but I have no reason to believe it was the cause.

**Comment by RobertBColton** [comment] 2020-07-20 19:12
I am going to close this one out now as I know it has long been fixed. I am not sure the problem was exactly what we originally thought, because the resource frames are being disposed. I think the issue is the links themselves were listening to the map, which is not disposed because it's part of the model.

I did a good thorough search over our code base to check all the places property links are being used, where they are made, where factories are being constructed, and I'm pretty sure we aren't missing any necessary cleanup. There's basically three patterns of using this link API in LateralGM. The first is constructor based where the super frame constructor creates the link factory and when the frame is disposed it clears all the links. The second is the room with selected instances and the font frame with selected character ranges where old links are removed and a new factory is constructed every time the selection changes. By removing the links first I am pretty sure that ensures they are GC'd. The third and final way is some of the still-static frames like game information which are never disposed, who tell the property factory to set the map when they are reverted, which I know does clean up the listeners.

I decided to still make f0a0da7bd310cc87d9398b599774b7e723666057 as an optimization to keep this interface clean and understandable. It didn't even need to be that way and was just a result of me fixing two different aspects of this at different times. Also #475 still remains to be fixed if it was in fact related to this.

**Closed by RobertBColton** 2020-07-20 19:12 UTC
Labels: Bug, Confirmed, Editor, Error, Pertinent, Reproducible
